from .config import (
    WALKER_S2_CFG,
    WALKER_S2_HOME_POSE,
    WALKER_S2_LEFT_ARM_JOINTS,
    WALKER_S2_RIGHT_ARM_JOINTS,
    WALKER_S2_LEFT_HAND_JOINTS,
    WALKER_S2_RIGHT_HAND_JOINTS,
    WALKER_S2_HEAD_JOINTS,
    WALKER_S2_WAIST_JOINTS,
    WALKER_S2_LEFT_LEG_JOINTS,
    WALKER_S2_RIGHT_LEG_JOINTS,
    WALKER_S2_USD_PATH,
)
