from .device_base import DeviceBase
from .action_process import preprocess_device_action, init_action_cfg

from .tiangong_pro.controller import TiangongProController
from .tiangong_pro.config import (
    TIANGONG_PRO_CFG,
    TIANGONG_PRO_HOME_POSE,
    TIANGONG_PRO_JOINT_LIMITS,
    TIANGONG_PRO_MIMIC_JOINTS,
    TIANGONG_PRO_LEFT_ARM_JOINTS,
    TIANGONG_PRO_RIGHT_ARM_JOINTS,
    TIANGONG_PRO_LEFT_HAND_JOINTS,
    TIANGONG_PRO_RIGHT_HAND_JOINTS,
    TIANGONG_PRO_HEAD_JOINTS,
    TIANGONG_PRO_WAIST_JOINTS,
    TIANGONG_PRO_LEFT_LEG_JOINTS,
    TIANGONG_PRO_RIGHT_LEG_JOINTS,
    TIANGONG_PRO_USD_PATH,
    ARM_HOME_POSE,
    HAND_HOME_POSE,
)
from .walker_s2.config import (
    WALKER_S2_CFG,
    WALKER_S2_HOME_POSE,
    WALKER_S2_LEFT_ARM_JOINTS,
    WALKER_S2_RIGHT_ARM_JOINTS,
    WALKER_S2_LEFT_HAND_JOINTS,
    WALKER_S2_RIGHT_HAND_JOINTS,
    WALKER_S2_HEAD_JOINTS,
    WALKER_S2_WAIST_JOINTS,
    WALKER_S2_LEFT_LEG_JOINTS,
    WALKER_S2_RIGHT_LEG_JOINTS,
    WALKER_S2_USD_PATH,
)
